import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
          flexDirection: "column",
          rowGap: "40px",
        }}
      >
        <Link href="/ssr-cache">Link to SSR-Cache Test Page</Link>
        <Link href="/next-cache">Link to Next-Config Test Page</Link>
        <Link href="/vercel-cache">Link to Vercel Test Page</Link>
      </div>
    </>
  );
}
